### ISSUE TITLE
Show item page needs to be styled

### ISSUE THREAD

**Issue by anazworth** [anazworth/orlando-recycling#8]

**Comment by zablon-oigo** [comment]
Hello, I'm interested in addressing this issue. Could you please assign it to me? I believe I can handle it effectively. 
Thank you!

**Comment by Aquint93** [comment]
> Hello, I'm interested in addressing this issue. Could you please assign it to me? I believe I can handle it effectively. Thank you!

@zablon-oigo Hi how's it going! Are you part of our Software Development class? If not you could contribute after our first milestone, we'll assign task to external after this.

**Comment by zablon-oigo** [comment]
> > Hello, I'm interested in addressing this issue. Could you please assign it to me? I believe I can handle it effectively. Thank you!
> 
> @zablon-oigo Hi how's it going! Are you part of our Software Development class? If not you could contribute after our first milestone, we'll assign task to external after this.

Hello @Aquint93, Thank you for reaching out! I'm not currently part of the Software Development class, I'm eager to contribute once the milestone is complete. Please keep me updated on any developments, and I'll be ready to contribute whenever you're ready.

**Comment by anazworth** [comment]
Fixed with #42
